export enum PermitEnum {
  CREATE_EVENTS = "CREATE_EVENTS",
  ATTEND_EVENTS = "ATTEND_EVENTS",
  CONSULT_EVENTS = "CONSULT_EVENTS",
  CONTENT_UPLOAD = "CONTENT_UPLOAD",
  CONTENT_VIEW = "CONTENT_VIEW",
  CONTENT_DOWNLOAD = "CONTENT_DOWNLOAD",
  PROFILE = "PROFILE",
  NOTIFICATIONS = "NOTIFICATIONS",
  CREATE_MILK_REQUEST = "CREATE_MILK_REQUEST",
  ASOCIATE_MILK_REQUEST = "ASOCIATE_MILK_REQUEST",
  TRACKING = "TRACKING",
  NEWS_UPLOAD = "NEWS_UPLOAD",
  NEWS_DOWNLOAD = "NEWS_DOWNLOAD"
}
